name: Build and deploy Node.js app to Azure Web App - travel-planner-rg-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build application
        working-directory: ./backend
        run: npm run build --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_967087E555B84161A1AB01543B30C326 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85BA7F85461E4D50910A5F5277595239 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C412E1B992FF4DB9961B504C8796FDD7 }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "travel-planner-rg-api"
          slot-name: "Production"
          package: ./backend